### ISSUE TITLE
HermanClassLoader.getResource("/") results in an IOError

### ISSUE THREAD

**Issue by jbunting** [digitalreasoning/herman#14]
It appears that the UrlClassLoader, when it cannot locate a resource in the given urls, just tries "herman:/" and attempts to open the connection.  Because of our "fail-fast" approach in the HermanUrlStreamHandler, this blows up since there is no "sub-protocol".  

``` java
java.io.IOError: java.net.MalformedURLException: no protocol: /
    at com.digitalreasoning.herman.HermanUrlStreamHandler.openConnection(HermanUrlStreamHandler.java:158)
    at java.net.URL.openConnection(URL.java:945)
    at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:472)
    at sun.misc.URLClassPath.findResource(URLClassPath.java:146)
    at java.net.URLClassLoader$2.run(URLClassLoader.java:385)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findResource(URLClassLoader.java:382)
    at java.lang.ClassLoader.getResource(ClassLoader.java:1002)
    at com.digitalreasoning.herman.HermanClassLoaderTest.testArtifact(HermanClassLoaderTest.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at net.peachjean.commons.test.junit.TmpDir$1.evaluate(TmpDir.java:36)
    at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:257)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
Caused by: java.net.MalformedURLException: no protocol: /
    at java.net.URL.<init>(URL.java:567)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URL.<init>(URL.java:413)
    at com.digitalreasoning.herman.HermanUrlStreamHandler.openConnection(HermanUrlStreamHandler.java:144)
    ... 29 more
```

HermanUrlStreamHandler needs to handle the case with no sub-protocol more gracefully.

**Comment by jbunting** [comment]
This is fixed in release 0.5.1.

**Comment by jmoyer256** [comment]
Glad this got closed, it was really bugging me. :-)
